# 游戏配置

#   ____             __ _
#  / ___|___  _ __  / _(_) __ _
# | |   / _ \| '_ \| |_| |/ _` |
# | |__| (_) | | | |  _| | (_| |
#  \____\___/|_| |_|_| |_|\__, |
#                         |___/

	Operate_timeout=10  # 玩家牌局出牌碰牌等操作超时，单位秒
	Trusteeship_timeout=1   # 玩家托管出牌超时，单位秒

	Db_addr="120.77.175.1:27017"            # 数据库地址
	Server_port=":8005"                       # 逻辑服端口
	Server_ip="127.0.0.1"                   # 本逻辑服的IP地址
	Oprof_port=":9005"
	Web_port=":8086"
	Pay_port=":7005"
	Pay_wx_pattern="/mahjong/wxpay/notice"
	Share_addr="http://yiiyu.cn/lanxi/wechat/download"

	Server_id=9                   # 本逻辑服的唯一编号
	Version="1.0.1"
	AdminPort = ":7229"          # 管理接口

	# 可选买子数量
    SelectMaiziCt = [0,1,2,3,4,5,6,7,8,9,10]
    # 可选牌局数量
    SelectGameCountCt = [8,16,1000]

    # 房卡价格
    Price  = [1,2]
    # 底分
    Ante = 2
